# Generated by Django 4.1.1 on 2022-10-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_tipo_sensor_tipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='tipos',
            new_name='tipo',
        ),
    ]
